### ISSUE TITLE
Requirements may not be up to date

### ISSUE THREAD

**Issue by iacolippo** [HazyResearch/butterfly#18]
Hi,

Thanks for the wonderful package! I was trying to install it with a Pytorch 1.7.1 but I get a bunch of errors during the compilation of the CUDA extension. After inspection of the source, I believe that the new implementation only works with Pytorch >1.8 (with which I could successfully install). 

The requirements still show `>=1.3` though, it might be good to update them or specify this in the README.

**Comment by tridao** [comment]
Thanks! I've updated the requirements to pytorch>=1.8
