### ISSUE TITLE
nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by yifanting** [HazyResearch/butterfly#23]
Hi, thank you for your code .when i install the pytorch extension
"cd butterfly/factor_multiply_fast    python setup.py install "，I have some trouble about it。
“nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture'
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
”
Which CUDA version are you using?
I use:
python 3.7
pytorch 1.8
CUDA  11.2

would appreciate any advice

**Comment by tridao** [comment]
Are you compiling for a GPU with compute capability 3.0? (https://en.wikipedia.org/wiki/CUDA)
I think the code needs some CUDA features that requires compute capability >= 3.5.

**Comment by yifanting** [comment]
Thank you for your help, and I have solved this problem.
Best wishes！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HazyResearch/butterfly"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 上午7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HazyResearch/butterfly] nvcc fatal   : Value 'sm_30' is not defined for option 'gpu-architecture' (#23)





 
Are you compiling for a GPU with compute capability 3.0? (https://en.wikipedia.org/wiki/CUDA)
 I think the code needs some CUDA features that requires compute capability &gt;= 3.5.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
