### ISSUE TITLE
torch_butterfly has CUDA version 0.0... incompatibility

### ISSUE THREAD

**Issue by nailon** [HazyResearch/butterfly#24]
Hi
I ran python setup.py install

then:
python
import torch_butterfly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nailon/miniconda3/envs/py38/lib/python3.8/site-packages/torch_butterfly-0.0.0-py3.8-linux-x86_64.egg/torch_butterfly/__init__.py", line 33, in <module>
    check_cuda_version()
  File "/home/nailon/miniconda3/envs/py38/lib/python3.8/site-packages/torch_butterfly-0.0.0-py3.8-linux-x86_64.egg/torch_butterfly/__init__.py", line 26, in check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torch_butterfly were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_butterfly has CUDA version 0.0. Please reinstall the torch_butterfly that matches your PyTorch install.
>>> 

Anybody?

**Comment by tridao** [comment]
Issue has been resolved through email.

**Comment by gunikavashisht13472** [comment]
Hi
I ran python setup.py install

then:
python
import torch_butterfly
And got:
RuntimeError: Detected that PyTorch and torch_butterfly were compiled with different CUDA versions. PyTorch has CUDA version 11.3 and torch_butterfly has CUDA version 0.0. Please reinstall the torch_butterfly that matches your PyTorch install

**Comment by gunikavashisht13472** [comment]
Could you let me know how can I resolve it?

**Comment by ThomasBoot** [comment]
Running into a similar issue (PyTorch has CUDA version 11.1 and torch_butterfly has CUDA version 11.2).
Would like to hear how you resolved this for the previous issue?

**Comment by abhishektyaagi** [comment]
@tridao @ThomasBoot @gunikavashisht13472 @nailon 
Were you able to resolve this issue? If yes, can you please share how you went about it
