### ISSUE TITLE
TORCH_LIBRARY not defined in butterfly.cpp

### ISSUE THREAD

**Issue by nailon** [HazyResearch/butterfly#25]
I just downloaded the latest version and tried to install but I get this

/home/nailon/vit-pytorch-nir/models/butterfly/csrc/butterfly.cpp:127:14: error: expected constructor, destructor, or type conversion before ‘(’ token
 TORCH_LIBRARY(torch_butterfly, m) {

where is TORCH_LIBRARY defined?

**Comment by tridao** [comment]
Issue has been resolved through email.
