### ISSUE TITLE
The latest version seems to have serious compatibility

### ISSUE THREAD

**Issue by nailon** [HazyResearch/butterfly#26]
I tried to install using torch1.9 and also 1.8, both fail with a ton of compilation problems.  Here is last line of error below.  Am I doing something wrong?  
Thanks

    /home/nailon/.local/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/nn/modules/conv.h:66:23: error: could not convert ‘torch::kLeakyReLU’ from ‘const torch::enumtype::kLeakyReLU’ to ‘torch::nn::init::NonlinearityType {aka c10::variant<torch::enumtype::kLinear, torch::enumtype::kConv1D, torch::enumtype::kConv2D, torch::enumtype::kConv3D, torch::enumtype::kConvTranspose1D, torch::enumtype::kConvTranspose2D, torch::enumtype::kConvTranspose3D, torch::enumtype::kSigmoid, torch::enumtype::kTanh, torch::enumtype::kReLU, torch::enumtype::kLeakyReLU>}’
    error: command '/usr/bin/nvcc' failed with exit status 1

**Comment by tridao** [comment]
Thanks, let me try to reproduce it.

**Comment by tridao** [comment]
Issue has been resolved through email.
