### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'origin

### ISSUE THREAD

**Issue by jasonli0707** [HazyResearch/butterfly#29]
Hi! I have tried to follow your instruction to install CUDA butterfly multiplication but kept receiving the same error message:
from torch_butterfly import Butterfly
  File "/dev/butterfly/torch_butterfly/__init__.py", line 9, in <module>
    torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
AttributeError: 'NoneType' object has no attribute 'origin'

Might you suggest how I could resolve it? Thank you!

My environment:
Python 3.8
Pytorch 1.8.0
CUDA 11.1
GeForce RTX 3090
GCC version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by kimwin2** [comment]
me too. do you have any solution about that?
