### ISSUE TITLE
Installing with pytorch 2.0

### ISSUE THREAD

**Issue by samar-khanna** [HazyResearch/butterfly#36]
Thanks to the authors for making their very helpful code publicly available. This is for those of you working with newer versions of torch.

Currently, if you try to run `python setup.py install` with torch 2.0 (python3.8, cuda 11.8), it will fail to compile. To solve this, you need to add just one line in `setup.py` on L30:

```
        nvcc_flags += ['-std=c++14']
```

EDIT: This actually didn't work, it seemed to compile for me because it clashed with an existing build but fails if I try to build from scratch.

**Comment by bytesnake** [comment]
replacing dynamic dispatching with restricted version from ATen works for me (I also had to downgrade gcc to 10 https://github.com/NVlabs/instant-ngp/issues/119)

```c++
#undef AT_DISPATCH_FLOATING_AND_COMPLEX_TYPES
#define AT_DISPATCH_FLOATING_AND_COMPLEX_TYPES(TYPE, NAME, ...)                                  \
  AT_DISPATCH_SWITCH(TYPE,NAME,                                           \
      AT_DISPATCH_CASE(at::ScalarType::ComplexFloat, __VA_ARGS__) \
      AT_DISPATCH_CASE(at::ScalarType::Float, __VA_ARGS__))
```
